theme:
  name: 'material'
  logo:
    icon: 'format_shapes'
  feature:
    tabs: false
  palette:
    primary: 'indigo'
    accent: 'indigo'
  favicon: 'img/a.png'

extra:
  search:
    tokenizer: '[\s\-\.]+'

use_directory_urls: false

site_name: Microservices Framework 

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
      linenums: true
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

pages:
- Home: 'index.md'
- Setup Instructions:
    - 'Workspace' : 'setup_instruction/workspace.md'
    - 'API' : 'setup_instruction/api.md'
- Developer Guide:
    - 'Request Validation': 'user-guide/input-validation.md'
    - 'Titan Query': 'user-guide/titan-query.md'
    - 'HBase Data Load': 'user-guide/hbase-load.md'
    - 'REST Response': 'user-guide/json-response.md'
- About:
    - 'About': 'about/about.md'
    - 'Release Notes': 'about/release-notes.md'
- Wiki:
    - 'Markdown': 'help/markdown.md'
    - 'Block Style': 'help/block-style.md'
    - 'Code Highlight': 'help/code-highlight.md'
    - 'Footnotes': 'help/footnotes.md'
    - 'Extensions': 'help/extensions.md'


extra_css:
#    - css/atom-one-light.min.css
    - css/theme.css

#extra_javascript:
#    - js/highlight.min.js
#    - js/highlight_code.js